spring.application.name=skillforge-payment-backend
server.port=9090

# Razorpay TEST credentials
razorpay.key-id=rzp_live_TXUP6MoEeX0Sf1
razorpay.key-secret=oE4uPZF2vZa7vPUlHby6osTS

spring.jackson.serialization.indent_output=true
