spring.application.name=skillforge-payment-backend
server.port=9090

# Razorpay TEST credentials
razorpay.key-id=rzp_test_TQuzIa8frKzvSg
razorpay.key-secret=QE1krkv9fH3U2yHt39Ctre8H

spring.jackson.serialization.indent_output=true
